### ISSUE TITLE
Code ví dụ bị sai chữ HOA chữ thường

### ISSUE THREAD

**Issue by itvn9online** [zaloplatform/zalo-php-sdk#24]
Admin vui lòng sửa lại ví dụ trong readme nhé, có mấy chỗ sai viết HOA viết thường, nên lúc copy ví dụ để test mà không để ý kỹ thì debug chật vẩy.
Ví dụ:
```
$callbackUrl = "https://www.callbackack.com";
```
back viết thường nhưng đoạn gọi lại viết Back
```
$loginUrl = $helper->getLoginUrl($callBackUrl, $codeChallenge, $state); // This is login url
```
Tiếp quả này nữa:
```
$response = $zalo->get(ZaloEndpoint::API_GRAPH_ME, $accessToken, $params);
```
Đúng của nó là `Point` không phải `point`:
```
$response = $zalo->get(ZaloEndPoint::API_GRAPH_ME, $accessToken, $params);
```

**Comment by zaloplatform** [comment]
Chào @itvn9online ,
Hiện tại readme đã được cập nhật lại rồi ạ.
Cảm ơn sự đóng góp của bạn.
