### ISSUE TITLE
Phiên bản 4.0.3 không có Zalo\Util\PKCEUtil

### ISSUE THREAD

**Issue by binhuq** [zaloplatform/zalo-php-sdk#25]
<img width="878" alt="Screenshot 2023-09-26 at 17 23 01" src="https://github.com/zaloplatform/zalo-php-sdk/assets/5626445/fcd2375d-fcfb-4b4a-8b57-8cdcefbecc3f">
<img width="376" alt="Screenshot 2023-09-26 at 17 23 09" src="https://github.com/zaloplatform/zalo-php-sdk/assets/5626445/26e4b118-6b41-4eb7-9ba0-95c3ca79c71c">

Khi mình sử dụng composer composer require zaloplatform/zalo-php-sdk để install bản mới nhất 4.0.3 thì vẫn không thấy PKCEUtil dù doc và source trên github vẫn có

**Comment by zaloplatform** [comment]
Chào @binhuq,
Hiện tại đã update lại version 4.0.3.
Cảm ơn sự đóng góp của bạn.
