### ISSUE TITLE
Làm thế nào lấy user_id từ phone number.

### ISSUE THREAD

**Issue by hungvtitdng** [zaloplatform/zalo-php-sdk#27]
Tôi có khách hàng tới sử dụng dịch vụ và họ cho sdt để gởi thông báo tới họ. 
làm thế nào để tôi lấy được user_id để gởi thông báo tới họ

**Comment by b0yblake** [comment]
Bạn đã giải quyết được vấn đề này chưa? tôi cũng đang tìm cách
