### ISSUE TITLE
uid is invalid

### ISSUE THREAD

**Issue by tindoantrong** [zaloplatform/zalo-php-sdk#3]
Mình get bằng src này thì có id của user rồi
$response = $zalo->get(ZaloEndpoint::API_GRAPH_ME, $params, $accessToken);
$result = $response->getDecodedBody(); // result

$zalo_user_id = $result['id'];

Sau đó mình muốn gửi tin nhắn cho user này thì nó bị lỗi: uid is invalid
src như sau:
$data = array(
    'uid' => $zalo_user_id, // user id
    'message' => 'thử gửi tin nhắn từ But\'s Day'
);
$params = ['data' => $data];
$response = $zalo->post(ZaloEndpoint::API_OA_SEND_TEXT_MSG, $params);
$result = $response->getDecodedBody(); // result

var_dump($result);
=> kết quả:
array (size=2)
  'errorCode' => int -201
  'errorMsg' => string 'uid is invalid' (length=14)

Vậy làm sao để gửi tin nhắn cho 1 user được?

Cảm ơn!

**Comment by zaloplatform** [comment]
Chào bạn,
Zalo hiện có 2 loại API, Social API và Offical Account API,
user id lấy từ Social API không sử dụng được cho Offical Account API và ngược lại

**Comment by tindoantrong** [comment]
Cảm ơn đã response.
Nhưng làm sao để lấy được uid ở Offical Account API của các người quan tâm?

Lần nữa, xin cảm ơn.

**Comment by zaloplatform** [comment]
Bạn có thể nghe sự kiện webhook khi có user quan tâm Offical Account,
Hoặc sử dụng API get follower profile, sử dụng phone number để lấy thông tin user đã quan tâm OA nhé.
Chúc bạn thành công!

**Comment by tindoantrong** [comment]
Về uid is invalid đã fix được rồi nhé.

Thanks

**Comment by gabri-ns** [comment]
Tôi gặp vấn đề tương tự. Sử dụng từ webhook tôi vẫn nhận được lỗi này.
