### ISSUE TITLE
Phiên bản lỗi thời?

### ISSUE THREAD

**Issue by gabri-ns** [zaloplatform/zalo-php-sdk#9]
Có bản cập nhật nào không? Dường như kho lưu trữ này có tệp khác với những gì tôi nhận được từ asda. Không có lớp ZaloEndpoint trong kho lưu trữ này trong khi có một đề cập trong readme.md.

**Comment by tom1097** [comment]
thêm vô nha bạn:

`use Zalo\ZaloEndpoint; `

**Comment by gabri-ns** [comment]
Nó được cập nhật vào ngày 29 tháng 7
